# Check the list of patients
GET http://localhost:3000/patients HTTP/1.1

###
# Get the patient with id 1
GET http://localhost:3000/patients/2 HTTP/1.1

###
# Get the patient with niis 781203-123-45
GET http://localhost:3000/patients/niss/710318-123-45 HTTP/1.1

###
## create a patient
POST http://localhost:3000/patients/ HTTP/1.1
Content-Type: application/json

{
  "firstName": "Salome",
  "lastName": "Habib",
  "birthDate": "2005-18-7",
  "niss": "051801-123-45",
  "address": {
    "street": "Rue de la santé","number": "2",
    "zipCode": "1000", "city": "Bruxelles", "country": "Belgique"
  },
  "refDoctor": 2
}

###
## verify the patient has been created
GET http://localhost:3000/patients HTTP/1.1

###
## Update the patient (the birthDate was not correct)
PUT http://localhost:3000/patients HTTP/1.1
Content-Type: application/json

{
  "id":2,
  "firstName": "Salome",
  "lastName": "Habib",
  "birthDate": "2005-01-01",
  "niss": "654321",
  "address": {
    "street": "Rue de la santé","number": "2",
    "zipCode": "1000", "city": "Bruxelles", "country": "Belgique"
  },
  "refDoctor": 2
}

###
## Delete the new patient
DELETE http://localhost:3000/patients?id=2 HTTP/1.1

# Get the patient with niss 640511-123-45
GET http://localhost:3000/patients/niss/640511-123-45 HTTP/1.1


###
# Get all the patient of the doctor
GET http://localhost:3000/patients/doctor/2 HTTP/1.1

###
# Get all the patient of a city
GET http://localhost:3000/patients/zipcode/7000 HTTP/1.1

###
# Get all the patients of a city and a doctor
GET http://localhost:3000/patients/doctor/2/zipcode/7000 HTTP/1.1
